name: bmmb_pajak_gadai_i
description: "Muamalat Pajak Gadai Islam (Ar-Rahnu)"

publish_to: 'none'
version: 2.0.2+10014

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  google_fonts: ^6.1.0
  http: ^1.2.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.5.0
  modal_progress_hud_nsn: ^0.5.1
  intl: ^0.20.2
  date_count_down: ^4.0.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  html: ^0.15.4

  # Icons
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flex_color_scheme: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/splash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/splash.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/splash.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/splash.png"

flutter:
  uses-material-design: true

  #---------- LOCAL ASSETS ----------#
  assets:
    - assets/images/

  #---------- LOCAL FONTS ----------#
fonts:
  - family: Montserrat
    fonts:
      - asset: asset/fonts/Montserrat-Regular.ttf
      - asset: asset/fonts/Montserrat-Light.ttf
      - weight: 300
      - asset: asset/fonts/Montserrat-Medium.ttf
      - weight: 500
      - asset: asset/fonts/Montserrat-SemiBold.ttf
      - weight: 600
      - asset: asset/fonts/Montserrat-Bold.ttf
      - weight: 700